on:
  workflow_call:
    inputs:
      aws_region:
        description: The AWS region target for deployment
        required: true
        type: string
      aws_replication_region:
        description: The AWS replication region target for deployment
        required: true
        type: string
      environment_name:
        description: The name of the environment configured in Github repository settings
        required: true
        type: string
    secrets:
      aws_s3_terraform_state_bucket_name:
        description: The AWS S3 bucket name containing Terraform backends, configured in Github repository settings
        required: true
        type: string

jobs:
  deploy:
    steps:
      - name: Clone the Git repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./terraform
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.aws_s3_terraform_state_bucket_name }}" \
            -backend-config="key=${{ jobs.deploy.environment }}.tfstate" \
            -backend-config="region=${{ inputs.aws_region }}"
        working-directory: ./terraform
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ inputs.aws_region }}" \
            -var="aws_replication_region=${{ inputs.aws_replication_region }}" \
            -var="environment=${{ inputs.environment_name }}"
        working-directory: ./terraform
