name: Deploy Infrastructure (DEV)

on:
  push:
    branches:
      - develop
      - feature/*

permissions:
  id-token: write    # This is required for requesting the JWT
  contents: read     # This is required for actions/checkout

jobs:
  Deploy:
    # TODO: support multi-environment deployments, perhaps make this a reusable job?
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Git repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./terraform
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.AWS_S3_TERRAFORM_STATE_BUCKET_NAME }}" \
            -backend-config="key=development.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}"
        working-directory: ./terraform
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="aws_replication_region=${{ vars.AWS_REPLICATION_REGION }}" \
            -var="environment=${{ vars.ENVIRONMENT_NAME }}"
        working-directory: ./terraform
