name: Deploy Infrastructure (DEV)

on:
  push:
    branches:
      - develop
      - feature/*

permissions:
  id-token: write    # This is required for requesting the JWT
  contents: read     # This is required for actions/checkout

jobs:
  # Due to the annoying inability for Github Actions to pass environment variables
  #  into reusable workflows, the following workaround is needed:
  #    https://github.com/orgs/community/discussions/26671#discussioncomment-4295807
  variables:
    environment: development
    outputs:
      aws_region: ${{ vars.AWS_REGION }}
      aws_replication_region: ${{ vars.AWS_REPLICATION_REGION }}
      aws_s3_terraform_state_object_key: ${{ vars.AWS_S3_TERRAFORM_STATE_OBJECT_KEY }}
      environment_name: ${{ vars.ENVIRONMENT_NAME }}
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Exposing environment variables: https://github.com/orgs/community/discussions/26671#discussioncomment-4295807"'
  deploy:
    needs: variables
    uses: ./.github/workflows/deploy.yml
    with:
      aws_region: ${{ needs.variables.outputs.aws_region }}
      aws_replication_region: ${{ needs.variables.outputs.aws_replication_region }}
      aws_s3_terraform_state_object_key: ${{ needs.variables.outputs.aws_s3_terraform_state_object_key }}
      environment_name: ${{ needs.variables.outputs.environment_name }}
    secrets:
      aws_s3_terraform_state_bucket_name: ${{ secrets.AWS_S3_TERRAFORM_STATE_BUCKET_NAME }}
